name: SecondPlugin
version: '${project.version}'
main: me.spengui.secondplugin.SecondPlugin
api-version: 1.16
authors: [ SpenGUI ]
description: this is my second plugin
website: https://www.youtube.com/channel/UCbOSK7plfCiilId5haEq7Zg
